#!/bin/bash

###############################################################################
# Includes and defines

projectName=bg-core

source /usr/lib/bg_core.sh
import Config.PluginType ;$L1;$L2

cmds="list report check apply runAll activate deactivate"


###############################################################################
# Functions

# inspect the command line and if sudo is required set user="root"
# set group="<someGroup" if known. Typically the group should not be hardcoded
# see man bg-overviewOutOfBandScriptFunctions for details
function oob_getRequiredUserAndGroup()
{
	bgBCParse "<glean>" "$@"; set -- "${posWords[@]:1}"

	local cmd="$1"
	case $cmd in
		activate)   echo "root" ;;
		deactivate) echo "root" ;;
		*) echo "" ;;
	esac
}

# Use this function to provide BC suggestions for positional parameters
# see man bg-overviewOutOfBandScriptFunctions for details
function printBashCompletion()
{
	local words cword cur prev optWords posWords posCwords
	parseForBashCompletion --compat2 words cword cur prev optWords posWords posCwords "$@"

	local cmd="${posWords[1]}"
	local pluginID="${posWords[2]}"

	case $cmd:$posCwords in
		*:1) echo "$cmds" ;;

		list:*) echo "--types --short --full --tree --list" ;;

		check:2) echo "<ConfigPluginName>"; $Config::list --short ;;
		apply:2) echo "<ConfigPluginName>"; $Config::list --short ;;

		activate:2)   echo "<ConfigPluginName>"; $Config::list --short ;;
		deactivate:2) echo "<ConfigPluginName>"; $Config::list --short ;;
	esac
	exit
}



###############################################################################
# Input handling

invokeOutOfBandSystem "$@"
verbosity=1
while [ $# -gt 0 ]; do case $1 in
	*)  bgOptionsEndLoop "$@" && break; set -- "${bgOptionsExpandedOpts[@]}"; esac; shift;
done


###############################################################################
# Main script


cmd="$1"; shift

case ${cmd:-report} in
	list)         $Config::list       "$@" ;;
	report)       $Config::report     "$@" ;;
	activate)     $Config::activate   "$@" ;;
	deactivate)   $Config::deactivate "$@" ;;
	check)        $Config::check      "$@" ;;
	apply)        $Config::apply      "$@" ;;
	runAll)       $Config::runAll     "$@" ;;
	*) assertError "unknown command '$cmd'"
esac
