
###############################################################################################################################
## bg_awkDataQueries.sh:awkData_lookup: start
## expect: 

##----------
## setup
##     | cmd> makeTestData
##     | cmd> export bgVinstalledManifest="$utDataFolder/manifest"
##     | cmd> cat "$bgVinstalledManifest"
##     | ut awkDataSchema type1                /tmp/tmp.<redacted>
##     | ut template      awkDataTblFmt.wiki   /tmp/tmp.<redacted>

##----------
## test
cmd> awkData_query type1 one:blue
      blue     2              
cmd> awkData_query type1.all two:1
       red     1              
cmd> awkData_query type1.one two:1
red
cmd> awkData_query -H type1
[2m[7m       one[0m [2m[7m  two[0m [2m[7m        three[0m
       red     1              
      blue     2              
     green     3              
cmd> awkData_query -e type1
       red     1            --
      blue     2            --
     green     3            --
cmd> awkData_query -w type1
{| class=\"wikitable sortable\"
|-
|        red ||     1 ||              
|-
|       blue ||     2 ||              
|-
|      green ||     3 ||              
|}

## bg_awkDataQueries.sh:awkData_lookup: finished
###############################################################################################################################

